### ISSUE TITLE
List of compliant national DGC gateways

### ISSUE THREAD

**Issue by grieshofer** [eu-digital-green-certificates/dgc-lib#62]
## List of compliant national DGC gateways

I'm following the development of the DGC libraries with great interest and I'd like to thank the community for steadily improving the respositories. Currently I am trying to implement the DGCG connector for easier retrieval of trusted certificates and business rules. Sadly, I did not find any list of compliant national gateways at the moment. In a longer discussion (https://github.com/eu-digital-green-certificates/dgc-participating-countries/issues/10) various implementations were mentioned, but I refuse to implement a different logic per country (or even provider) when there is an open standard.

Does anyone have a source with publicly available gateways (or at least one trustworthy source with a proper documentation)? 

### Sources I've already screened

- https://dgc.a-sit.at/ehn/ (sadly, no documentation)
- https://github.com/eu-digital-green-certificates
- https://github.com/ehn-dcc-development
- https://github.com/panzi/verify-ehc/blob/main/verify_ehc.py (great work!)

**Comment by f11h** [comment]
Hi @grieshofer , from dev team I can say that we do not have an overview about the current implementations of the national backends.
But I can let this ticket open that maybe somebody else has some information.
But I don't think that you will get any response here because this repo is more or less a "hidden place" with not so much visitors.
